[package]
name = "ant-system"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = "5.5.1"
ndarray = "0.16.1"
ndarray-linalg = "0.17.0"
rand = "0.9.2"
rand_distr = "0.5.1"
matrix = "0.22.0"
itertools = "0.14.0"
